name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # フロントエンド
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci
        working-directory: onehouse

      - name: Build frontend assets
        run: npm run build
        working-directory: onehouse

      - name: Upload frontend assets
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "onehouse/public/build"
          target: "${{ secrets.SERVER_PATH }}/public"

        # バックエンド
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            git pull origin main

            composer install --optimize-autoloader --no-dev
            php artisan optimize:clear
            php artisan migrate --force
            sudo systemctl reload httpd
